[package]
name = "rusterria"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
avian2d = "0.1"
bevy_asset_loader = "0.21.0"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 3
